apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingest.uploadFullname" . }}
  labels:
    {{- include "ingest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.tusd.enabled }}
    - port: {{ .Values.tusd.port }}
      targetPort: tus
      protocol: TCP
      name: tus
    {{- end }}
  selector:
    {{- include "ingest.selectorLabels" . | nindent 4 }}
