# generated by datamodel-codegen:
#   filename:  ffprobe.json

from __future__ import annotations

from typing import Optional, Union

from pydantic import BaseModel, ConfigDict


class ProgramVersion(BaseModel):
    version: str
    copyright: str
    compiler_ident: str
    configuration: str


class LibraryVersion(BaseModel):
    name: str
    major: int
    minor: int
    micro: int
    version: int
    ident: str


class PixelFormat(BaseModel):
    pass


class Packet(BaseModel):
    pass


class Frame(BaseModel):
    pass


class Format(BaseModel):
    filename: str
    nb_streams: int
    nb_programs: int
    format_name: str
    probe_score: int
    format_long_name: Optional[str] = None
    start_time: Optional[str] = None
    duration: Optional[str] = None
    size: Optional[str] = None
    bit_rate: Optional[str] = None
    tags: Optional[dict[str, str]] = None


class Chapter(BaseModel):
    id: int
    time_base: str
    start: int
    start_time: str
    end: int
    end_time: str
    tags: Optional[dict[str, str]] = None


class Disposition(BaseModel):
    default: Optional[int] = None
    dub: Optional[int] = None
    original: Optional[int] = None
    comment: Optional[int] = None
    lyrics: Optional[int] = None
    karaoke: Optional[int] = None
    forced: Optional[int] = None
    hearing_impaired: Optional[int] = None
    visual_impaired: Optional[int] = None
    clean_effects: Optional[int] = None
    attached_pic: Optional[int] = None
    timed_thumbnails: Optional[int] = None
    captions: Optional[int] = None
    descriptions: Optional[int] = None
    metadata: Optional[int] = None
    dependent: Optional[int] = None
    still_image: Optional[int] = None


class Error(BaseModel):
    code: int
    string: str


class Stream(BaseModel):
    index: int
    codec_tag_string: str
    codec_tag: str
    codec_name: Optional[str] = None
    codec_long_name: Optional[str] = None
    profile: Optional[str] = None
    codec_type: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None
    coded_width: Optional[int] = None
    coded_height: Optional[int] = None
    closed_captions: Optional[int] = None
    has_b_frames: Optional[int] = None
    sample_aspect_ratio: Optional[str] = None
    display_aspect_ratio: Optional[str] = None
    pix_fmt: Optional[str] = None
    level: Optional[int] = None
    color_range: Optional[str] = None
    color_space: Optional[str] = None
    color_transfer: Optional[str] = None
    color_primaries: Optional[str] = None
    chroma_location: Optional[str] = None
    field_order: Optional[str] = None
    refs: Optional[int] = None
    sample_fmt: Optional[str] = None
    sample_rate: Optional[str] = None
    channels: Optional[int] = None
    channel_layout: Optional[str] = None
    bits_per_sample: Optional[int] = None
    id: Optional[str] = None
    r_frame_rate: Optional[str] = None
    avg_frame_rate: Optional[str] = None
    time_base: Optional[str] = None
    start_pts: Optional[int] = None
    start_time: Optional[str] = None
    duration_ts: Optional[int] = None
    duration: Optional[str] = None
    bit_rate: Optional[str] = None
    max_bit_rate: Optional[str] = None
    bits_per_raw_sample: Optional[str] = None
    nb_frames: Optional[str] = None
    nb_read_frames: Optional[str] = None
    nb_read_packets: Optional[str] = None
    disposition: Optional[Disposition] = None
    tags: Optional[dict[str, str]] = None


class Program(BaseModel):
    program_id: int
    program_num: int
    nb_streams: int
    pmt_pid: int
    pcr_pid: int
    start_pts: int
    start_time: str
    end_pts: int
    end_time: str
    streams: list[Stream]
    tags: Optional[dict[str, str]] = None


class FfprobeOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    program_version: Optional[ProgramVersion] = None
    library_version: Optional[list[LibraryVersion]] = None
    pixel_formats: Optional[list[PixelFormat]] = None
    packets: Optional[list[Packet]] = None
    frames: Optional[list[Frame]] = None
    packets_and_frames: Optional[list[Union[Packet, Frame]]] = None
    programs: Optional[list[Program]] = None
    streams: Optional[list[Stream]] = None
    format: Optional[Format] = None
    chapters: Optional[list[Chapter]] = None
    error: Optional[Error] = None
