# generated by datamodel-codegen:
#   filename:  ffprobe.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class ProgramVersion(BaseModel):
    version: str
    copyright: str
    compiler_ident: str
    configuration: str


class LibraryVersion(BaseModel):
    name: str
    major: int
    minor: int
    micro: int
    version: int
    ident: str


class PixelFormat(BaseModel):
    pass


class Packet(BaseModel):
    pass


class Frame(BaseModel):
    pass


class Format(BaseModel):
    filename: str
    nb_streams: int
    nb_programs: int
    format_name: str
    probe_score: int
    format_long_name: str | None = None
    start_time: str | None = None
    duration: str | None = None
    size: str | None = None
    bit_rate: str | None = None
    tags: dict[str, str] | None = None


class Chapter(BaseModel):
    id: int
    time_base: str
    start: int
    start_time: str
    end: int
    end_time: str
    tags: dict[str, str] | None = None


class Disposition(BaseModel):
    default: int | None = None
    dub: int | None = None
    original: int | None = None
    comment: int | None = None
    lyrics: int | None = None
    karaoke: int | None = None
    forced: int | None = None
    hearing_impaired: int | None = None
    visual_impaired: int | None = None
    clean_effects: int | None = None
    attached_pic: int | None = None
    timed_thumbnails: int | None = None
    captions: int | None = None
    descriptions: int | None = None
    metadata: int | None = None
    dependent: int | None = None
    still_image: int | None = None


class Error(BaseModel):
    code: int
    string: str


class Stream(BaseModel):
    index: int
    codec_tag_string: str
    codec_tag: str
    codec_name: str | None = None
    codec_long_name: str | None = None
    profile: str | None = None
    codec_type: str | None = None
    width: int | None = None
    height: int | None = None
    coded_width: int | None = None
    coded_height: int | None = None
    closed_captions: int | None = None
    has_b_frames: int | None = None
    sample_aspect_ratio: str | None = None
    display_aspect_ratio: str | None = None
    pix_fmt: str | None = None
    level: int | None = None
    color_range: str | None = None
    color_space: str | None = None
    color_transfer: str | None = None
    color_primaries: str | None = None
    chroma_location: str | None = None
    field_order: str | None = None
    refs: int | None = None
    sample_fmt: str | None = None
    sample_rate: str | None = None
    channels: int | None = None
    channel_layout: str | None = None
    bits_per_sample: int | None = None
    id: str | None = None
    r_frame_rate: str | None = None
    avg_frame_rate: str | None = None
    time_base: str | None = None
    start_pts: int | None = None
    start_time: str | None = None
    duration_ts: int | None = None
    duration: str | None = None
    bit_rate: str | None = None
    max_bit_rate: str | None = None
    bits_per_raw_sample: str | None = None
    nb_frames: str | None = None
    nb_read_frames: str | None = None
    nb_read_packets: str | None = None
    disposition: Disposition | None = None
    tags: dict[str, str] | None = None


class Program(BaseModel):
    program_id: int
    program_num: int
    nb_streams: int
    pmt_pid: int
    pcr_pid: int
    start_pts: int
    start_time: str
    end_pts: int
    end_time: str
    streams: list[Stream]
    tags: dict[str, str] | None = None


class FfprobeOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    program_version: ProgramVersion | None = None
    library_version: list[LibraryVersion] | None = None
    pixel_formats: list[PixelFormat] | None = None
    packets: list[Packet] | None = None
    frames: list[Frame] | None = None
    packets_and_frames: list[Packet | Frame] | None = None
    programs: list[Program] | None = None
    streams: list[Stream] | None = None
    format: Format | None = None
    chapters: list[Chapter] | None = None
    error: Error | None = None
